package com.github.fmabap.amdpprettyprinter.prettyprinter;

import static org.junit.Assert.assertEquals;

import java.util.List;

import org.junit.Test;

/**
 * Tests for full SQLScript method formatting.
 *
 * Converted from ABAP test methods:
 * with_sql_script, with_sql_script_no_lb_at_comma
 */
public class PrettyPrinterSqlScriptTest extends PrettyPrinterTestBase {

    // ------------------------------------------------------------------
    // Shared source (used in both tests)
    // ------------------------------------------------------------------

    /**
     * A realistic AMDP class containing both a plain ABAP method and a
     * SQLScript method with many different SQL constructs.
     */
    private static List<String> buildFullSqlScriptSource() {
        // @formatter:off
        return lines(
            "",
            " CLASS zcl_app_test_amdp DEFINITION",
            "   PUBLIC",
            "   FINAL",
            "   CREATE PUBLIC .",
            " ",
            "   PUBLIC SECTION.",
            " ",
            "   INTERFACES if_amdp_marker_hdb.",
            " ",
            "   CLASS-METHODS sel_data.",
            " ",
            "   CLASS-METHODS write_data.",
            " ",
            "   PROTECTED SECTION.",
            "   PRIVATE SECTION.",
            " ENDCLASS.",
            " ",
            " ",
            " ",
            " CLASS zcl_app_test_amdp IMPLEMENTATION.",
            " ",
            "   METHOD write_data.",
            "   \"Hello World 'keine Ahnung' 'bla",
            "   WRITE / 'Hello World'. \"Kommentar",
            "   ENDMETHOD.",
            " ",
            "   METHOD sel_data",
            "   BY DATABASE PROCEDURE FOR HDB LANGUAGE SQLSCRIPT",
            "   \"opt",
            "* sqlscript",
            "   OPTIONS READ-ONLY",
            "   USING sflight. ",
            "  -- Flight",
            "  declare lv_bla nvarchar(4);",
            "  lv_bla = 'BlA';                        ---Blub",
            " ",
            "  call \"CLASS=>PROCESS\"(",
            "       iv_capid     => :IV_CAPID,              --Blub",
            "    iv_base_step     =>     :IV_BASE_STEP,     ",
            "       cv_operation_id =>     cv_operation_id ",
            "          ); ",
            " ",
            "   lt_carrid2 = select \"SFLIGHT\".\"CARRID\" from sflight;",
            " ",
            "   lt_sflight = select * from sflight;",
            " ",
            "   lt_carrid = select \"CARRID\" from sflight;",
            " ",
            "   lt_carrid2 = select \"SFLIGHT\".\"CARRID\" from sflight;",
            "  lt_carrid3 = select max( concat( \"SFLIGHT\".\"CARRID\", connid ) )from sflight; ",
            " lt_carrid4 = select max( ( concat( sflight, connid ) ) )from sflight; ",
            " lt_carrid4 = select max( ( concat( sflight, connid )))from sflight; ",
            " lt_carrid5 = select concat( sflight, connid ) from sflight; ",
            " lt_carrid5 = select concat( sflight, connid ) from sflight with hint ( NO_INLINE ); ",
            " lt_carrid5 = select concat( sflight, connid ) from sflight with hint ( NO_INLINE",
            "  ); ",
            " lt_carrid5 = select concat( sflight, connid ) from sflight with hint ( NO_INLINE",
            "  ) ; ",
            " lt_carrid5 = select concat( sflight, connid ) from sflight; ",
            " ",
            "*lt_test = select 'Bla Blup Data' from public.dummy;",
            "   lt_test = select 'Bla Blup Data' from public.dummy;",
            " ",
            "   -- Hello World 'keine Ahnung' 'bla blub'",
            "   lt_test2 = select 'Bla Blup Data' from public.dummy; /*schaun mer mal */",
            " ",
            "   /* schaun mer",
            "   noch mehr */",
            " ",
            "   lt_test3 = select 'Bla Blup Data' from public.dummy; /*schaun mer mal */",
            " ",
            "   lt_test3 = select 'Bla Blup Data' from public.dummy; -- schaun mer mal",
            " ",
            " et_bla_part = select :bal,",
            "                :LT_bla_part.\"/BLA/KEY_REF\", ",
            "                :LT_bla_part.\"/BLA/VRS_REF\" ",
            "             from :LT_bla_part ",
            "           inner join \"/BLA/MAT_TYP_USE\" as blaclsp ",
            "               on blaclsp.mandt = session_context( 'CLIENT') ",
            "              and blaclsp.matnr = :LT_bla_part.matnr ",
            "           union  all ",
            "             select :LT_bla_part.run_no, ",
            "                :LT_bla_part.\"/BLA/KEY_REF\", ",
            "                :LT_bla_part.\"/BLA/VRS_REF\" ",
            "             from :LT_bla_part ",
            "            where not exists( select 1 ",
            "                      from \"/BLA/MAT_TYP_USE\" as blaclsp ",
            "                       where blaclsp.mandt = session_context( 'CLIENT') ",
            "                       and blaclsp.matnr = :LT_bla_part.matnr ",
            "                    );",
            " ",
            "  Lt_test4 =  select carrid, connid, fldate",
            "   from sflight",
            "   where sflight.mandt =  SESSION_CONTEXT('CLIENT')",
            "   and sflight.connid = 'LH' union all",
            "   select spfli.carrid, spfli.connid, sflight.FLDATE",
            "   from spfli left outer join sflight",
            "   on sflight.mandt = spfli.mandt",
            "   and sflight.CARRID = spfli.carrid",
            "   and sflight.CONNID = spfli.connid",
            "   where spfli.mandt = SESSION_CONTEXT('CLIENT')",
            "   and spfli.carrid = 'AB' union all",
            "   select spfli.carrid, spfli.connid, sflight.FLDATE",
            "   from spfli inner join sflight",
            "   on sflight.mandt = spfli.mandt",
            "   and sflight.CARRID = spfli.carrid",
            "   and sflight.CONNID = spfli.connid",
            "   where spfli.mandt = SESSION_CONTEXT('CLIENT')",
            "   and spfli.carrid = 'AB';",
            " ",
            " lt_spfli1 = SELECT carrid, connid, countryfr, countryto,",
            " ROW_NUMBER ( ) OVER( ORDER BY \"CARRID\", CONNID asc ) AS \"ROW_ID\"",
            " FROM SPFLI WHERE mandt = session_context( 'CLIENT' );",
            " ",
            " ",
            " lt_spfli2 = SELECT carrid, connid, countryfr, countryto,",
            " ROW_NUMBER ( ) OVER( PARTITION BY carrid, connid ORDER BY \"CARRID\", CONNID asc ) AS \"ROW_ID\"",
            " FROM SPFLI WHERE mandt = session_context( 'CLIENT' );",
            "   --ENDMETHOD.",
            "   ENDMETHOD.",
            " ENDCLASS."
        );
        // @formatter:on
    }

    // ------------------------------------------------------------------
    // with_sql_script (lineBreakAfterCommaReq = true)
    // ------------------------------------------------------------------

    @Test
    public void withSqlScript() throws Exception {
        // @formatter:off
        List<String> expected = rtrim(lines(
            "",
            " CLASS zcl_app_test_amdp DEFINITION",
            "   PUBLIC",
            "   FINAL",
            "   CREATE PUBLIC .",
            " ",
            "   PUBLIC SECTION.",
            " ",
            "   INTERFACES if_amdp_marker_hdb.",
            " ",
            "   CLASS-METHODS sel_data.",
            " ",
            "   CLASS-METHODS write_data.",
            " ",
            "   PROTECTED SECTION.",
            "   PRIVATE SECTION.",
            " ENDCLASS.",
            " ",
            " ",
            " ",
            " CLASS zcl_app_test_amdp IMPLEMENTATION.",
            " ",
            "   METHOD write_data.",
            "   \"Hello World 'keine Ahnung' 'bla",
            "   WRITE / 'Hello World'. \"Kommentar",
            "   ENDMETHOD.",
            " ",
            "   METHOD sel_data",
            "   BY DATABASE PROCEDURE FOR HDB LANGUAGE SQLSCRIPT",
            "   \"opt",
            "* sqlscript",
            "   OPTIONS READ-ONLY",
            "   USING sflight. ",
            "    -- Flight ",
            "    DECLARE lv_bla NVARCHAR(4); ",
            "    lv_bla = 'BlA';                        ---Blub ",
            "",
            "    CALL \"CLASS=>PROCESS\"( ",
            "             iv_capid        => :iv_capid,              --Blub ",
            "             iv_base_step    => :iv_base_step, ",
            "             cv_operation_id => cv_operation_id ",
            "             ); ",
            "",
            "    lt_carrid2 = SELECT \"SFLIGHT\".\"CARRID\" ",
            "                   FROM sflight; ",
            "",
            "    lt_sflight = SELECT * ",
            "                   FROM sflight; ",
            "",
            "    lt_carrid = SELECT \"CARRID\" ",
            "                  FROM sflight; ",
            "",
            "    lt_carrid2 = SELECT \"SFLIGHT\".\"CARRID\" ",
            "                   FROM sflight; ",
            "    lt_carrid3 = SELECT MAX( CONCAT( \"SFLIGHT\".\"CARRID\", ",
            "                                     connid ",
            "                                   ) ",
            "                           ) ",
            "                   FROM sflight; ",
            "    lt_carrid4 = SELECT MAX( ",
            "                             ( CONCAT( sflight, ",
            "                                       connid ",
            "                                     ) ",
            "                             ) ",
            "                           ) ",
            "                   FROM sflight; ",
            "    lt_carrid4 = SELECT MAX( ",
            "                             ( CONCAT( sflight, ",
            "                                       connid ",
            "                                     )",
            "                             )",
            "                           ) ",
            "                   FROM sflight; ",
            "    lt_carrid5 = SELECT CONCAT( sflight, ",
            "                                connid ",
            "                              ) ",
            "                   FROM sflight; ",
            "    lt_carrid5 = SELECT CONCAT( sflight, ",
            "                                connid ",
            "                              ) ",
            "                   FROM sflight WITH HINT ( no_inline ); ",
            "    lt_carrid5 = SELECT CONCAT( sflight, ",
            "                                connid ",
            "                              ) ",
            "                   FROM sflight WITH HINT ( no_inline",
            "                                          ); ",
            "    lt_carrid5 = SELECT CONCAT( sflight, ",
            "                                connid ",
            "                              ) ",
            "                   FROM sflight WITH HINT ( no_inline",
            "                                          ) ; ",
            "    lt_carrid5 = SELECT CONCAT( sflight, ",
            "                                connid ",
            "                              ) ",
            "                   FROM sflight; ",
            "",
            "*lt_test = select 'Bla Blup Data' from public.dummy; ",
            "    lt_test = SELECT 'Bla Blup Data' ",
            "                FROM public.dummy; ",
            "",
            "    -- Hello World 'keine Ahnung' 'bla blub' ",
            "    lt_test2 = SELECT 'Bla Blup Data' ",
            "                 FROM public.dummy; /*schaun mer mal */ ",
            "",
            "    /* schaun mer",
            "   noch mehr */ ",
            "",
            "    lt_test3 = SELECT 'Bla Blup Data' ",
            "                 FROM public.dummy; /*schaun mer mal */ ",
            "",
            "    lt_test3 = SELECT 'Bla Blup Data' ",
            "                 FROM public.dummy; -- schaun mer mal ",
            "",
            "    et_bla_part =     SELECT :bal, ",
            "                             :lt_bla_part.\"/BLA/KEY_REF\", ",
            "                             :lt_bla_part.\"/BLA/VRS_REF\" ",
            "                        FROM :lt_bla_part ",
            "                  INNER JOIN \"/BLA/MAT_TYP_USE\" AS blaclsp ",
            "                          ON blaclsp.mandt = SESSION_CONTEXT( 'CLIENT') ",
            "                         AND blaclsp.matnr = :lt_bla_part.matnr ",
            "                   UNION ALL ",
            "                      SELECT :lt_bla_part.run_no, ",
            "                             :lt_bla_part.\"/BLA/KEY_REF\", ",
            "                             :lt_bla_part.\"/BLA/VRS_REF\" ",
            "                        FROM :lt_bla_part ",
            "                       WHERE NOT EXISTS( SELECT 1 ",
            "                                           FROM \"/BLA/MAT_TYP_USE\" AS blaclsp ",
            "                                          WHERE blaclsp.mandt = SESSION_CONTEXT( 'CLIENT') ",
            "                                            AND blaclsp.matnr = :lt_bla_part.matnr ",
            "                                       ); ",
            "",
            "    lt_test4 =          SELECT carrid, ",
            "                               connid, ",
            "                               fldate ",
            "                          FROM sflight ",
            "                         WHERE sflight.mandt = SESSION_CONTEXT('CLIENT') ",
            "                           AND sflight.connid = 'LH' ",
            "                     UNION ALL ",
            "                        SELECT spfli.carrid, ",
            "                               spfli.connid, ",
            "                               sflight.fldate ",
            "                          FROM spfli ",
            "               LEFT OUTER JOIN sflight ",
            "                            ON sflight.mandt = spfli.mandt ",
            "                           AND sflight.carrid = spfli.carrid ",
            "                           AND sflight.connid = spfli.connid ",
            "                         WHERE spfli.mandt = SESSION_CONTEXT('CLIENT') ",
            "                           AND spfli.carrid = 'AB' ",
            "                     UNION ALL ",
            "                        SELECT spfli.carrid, ",
            "                               spfli.connid, ",
            "                               sflight.fldate ",
            "                          FROM spfli ",
            "                    INNER JOIN sflight ",
            "                            ON sflight.mandt = spfli.mandt ",
            "                           AND sflight.carrid = spfli.carrid ",
            "                           AND sflight.connid = spfli.connid ",
            "                         WHERE spfli.mandt = SESSION_CONTEXT('CLIENT') ",
            "                           AND spfli.carrid = 'AB'; ",
            "",
            "    lt_spfli1 = SELECT carrid, ",
            "                       connid, ",
            "                       countryfr, ",
            "                       countryto, ",
            "                       ROW_NUMBER ( ) OVER( ORDER BY \"CARRID\", ",
            "                                                     connid ASC ",
            "                                          ) AS \"ROW_ID\" ",
            "                  FROM spfli ",
            "                 WHERE mandt = SESSION_CONTEXT( 'CLIENT' ); ",
            "",
            "",
            "    lt_spfli2 = SELECT carrid, ",
            "                       connid, ",
            "                       countryfr, ",
            "                       countryto, ",
            "                       ROW_NUMBER ( ) OVER( PARTITION BY carrid, ",
            "                                                         connid ",
            "                                            ORDER BY \"CARRID\", ",
            "                                                     connid ASC ",
            "                                          ) AS \"ROW_ID\" ",
            "                  FROM spfli ",
            "                 WHERE mandt = SESSION_CONTEXT( 'CLIENT' ); ",
            "    --ENDMETHOD. ",
            "   ENDMETHOD.",
            " ENDCLASS."
        ));
        // @formatter:on

        assertEquals(expected, prettyPrint(buildFullSqlScriptSource(), standardSettings()));
    }

    // ------------------------------------------------------------------
    // with_sql_script_no_lb_at_comma (lineBreakAfterCommaReq = false)
    // ------------------------------------------------------------------

    @Test
    public void withSqlScriptNoLbAtComma() throws Exception {
        // @formatter:off
        List<String> expected = rtrim(lines(
            "",
            " CLASS zcl_app_test_amdp DEFINITION",
            "   PUBLIC",
            "   FINAL",
            "   CREATE PUBLIC .",
            " ",
            "   PUBLIC SECTION.",
            " ",
            "   INTERFACES if_amdp_marker_hdb.",
            " ",
            "   CLASS-METHODS sel_data.",
            " ",
            "   CLASS-METHODS write_data.",
            " ",
            "   PROTECTED SECTION.",
            "   PRIVATE SECTION.",
            " ENDCLASS.",
            " ",
            " ",
            " ",
            " CLASS zcl_app_test_amdp IMPLEMENTATION.",
            " ",
            "   METHOD write_data.",
            "   \"Hello World 'keine Ahnung' 'bla",
            "   WRITE / 'Hello World'. \"Kommentar",
            "   ENDMETHOD.",
            " ",
            "   METHOD sel_data",
            "   BY DATABASE PROCEDURE FOR HDB LANGUAGE SQLSCRIPT",
            "   \"opt",
            "* sqlscript",
            "   OPTIONS READ-ONLY",
            "   USING sflight. ",
            "    -- Flight ",
            "    DECLARE lv_bla NVARCHAR(4); ",
            "    lv_bla = 'BlA';                        ---Blub ",
            "",
            "    CALL \"CLASS=>PROCESS\"( iv_capid => :iv_capid,              --Blub ",
            "             iv_base_step => :iv_base_step, ",
            "             cv_operation_id => cv_operation_id ",
            "             ); ",
            "",
            "    lt_carrid2 = SELECT \"SFLIGHT\".\"CARRID\" ",
            "                   FROM sflight; ",
            "",
            "    lt_sflight = SELECT * ",
            "                   FROM sflight; ",
            "",
            "    lt_carrid = SELECT \"CARRID\" ",
            "                  FROM sflight; ",
            "",
            "    lt_carrid2 = SELECT \"SFLIGHT\".\"CARRID\" ",
            "                   FROM sflight; ",
            "    lt_carrid3 = SELECT MAX( CONCAT( \"SFLIGHT\".\"CARRID\", connid ) ) ",
            "                   FROM sflight; ",
            "    lt_carrid4 = SELECT MAX( ",
            "                             ( CONCAT( sflight, connid ) ) ",
            "                           ) ",
            "                   FROM sflight; ",
            "    lt_carrid4 = SELECT MAX( ",
            "                             ( CONCAT( sflight, connid ))",
            "                           ) ",
            "                   FROM sflight; ",
            "    lt_carrid5 = SELECT CONCAT( sflight, connid ) ",
            "                   FROM sflight; ",
            "    lt_carrid5 = SELECT CONCAT( sflight, connid ) ",
            "                   FROM sflight WITH HINT ( no_inline ); ",
            "    lt_carrid5 = SELECT CONCAT( sflight, connid ) ",
            "                   FROM sflight WITH HINT ( no_inline",
            "                                          ); ",
            "    lt_carrid5 = SELECT CONCAT( sflight, connid ) ",
            "                   FROM sflight WITH HINT ( no_inline",
            "                                          ) ; ",
            "    lt_carrid5 = SELECT CONCAT( sflight, connid ) ",
            "                   FROM sflight; ",
            "",
            "*lt_test = select 'Bla Blup Data' from public.dummy; ",
            "    lt_test = SELECT 'Bla Blup Data' ",
            "                FROM public.dummy; ",
            "",
            "    -- Hello World 'keine Ahnung' 'bla blub' ",
            "    lt_test2 = SELECT 'Bla Blup Data' ",
            "                 FROM public.dummy; /*schaun mer mal */ ",
            "",
            "    /* schaun mer",
            "   noch mehr */ ",
            "",
            "    lt_test3 = SELECT 'Bla Blup Data' ",
            "                 FROM public.dummy; /*schaun mer mal */ ",
            "",
            "    lt_test3 = SELECT 'Bla Blup Data' ",
            "                 FROM public.dummy; -- schaun mer mal ",
            "",
            "    et_bla_part =     SELECT :bal, ",
            "                             :lt_bla_part.\"/BLA/KEY_REF\", ",
            "                             :lt_bla_part.\"/BLA/VRS_REF\" ",
            "                        FROM :lt_bla_part ",
            "                  INNER JOIN \"/BLA/MAT_TYP_USE\" AS blaclsp ",
            "                          ON blaclsp.mandt = SESSION_CONTEXT( 'CLIENT') ",
            "                         AND blaclsp.matnr = :lt_bla_part.matnr ",
            "                   UNION ALL ",
            "                      SELECT :lt_bla_part.run_no, ",
            "                             :lt_bla_part.\"/BLA/KEY_REF\", ",
            "                             :lt_bla_part.\"/BLA/VRS_REF\" ",
            "                        FROM :lt_bla_part ",
            "                       WHERE NOT EXISTS( SELECT 1 ",
            "                                           FROM \"/BLA/MAT_TYP_USE\" AS blaclsp ",
            "                                          WHERE blaclsp.mandt = SESSION_CONTEXT( 'CLIENT') ",
            "                                            AND blaclsp.matnr = :lt_bla_part.matnr ",
            "                                       ); ",
            "",
            "    lt_test4 =          SELECT carrid, connid, fldate ",
            "                          FROM sflight ",
            "                         WHERE sflight.mandt = SESSION_CONTEXT('CLIENT') ",
            "                           AND sflight.connid = 'LH' ",
            "                     UNION ALL ",
            "                        SELECT spfli.carrid, spfli.connid, sflight.fldate ",
            "                          FROM spfli ",
            "               LEFT OUTER JOIN sflight ",
            "                            ON sflight.mandt = spfli.mandt ",
            "                           AND sflight.carrid = spfli.carrid ",
            "                           AND sflight.connid = spfli.connid ",
            "                         WHERE spfli.mandt = SESSION_CONTEXT('CLIENT') ",
            "                           AND spfli.carrid = 'AB' ",
            "                     UNION ALL ",
            "                        SELECT spfli.carrid, spfli.connid, sflight.fldate ",
            "                          FROM spfli ",
            "                    INNER JOIN sflight ",
            "                            ON sflight.mandt = spfli.mandt ",
            "                           AND sflight.carrid = spfli.carrid ",
            "                           AND sflight.connid = spfli.connid ",
            "                         WHERE spfli.mandt = SESSION_CONTEXT('CLIENT') ",
            "                           AND spfli.carrid = 'AB'; ",
            "",
            "    lt_spfli1 = SELECT carrid, connid, countryfr, countryto, ",
            "                       ROW_NUMBER ( ) OVER( ORDER BY \"CARRID\", connid ASC ) AS \"ROW_ID\" ",
            "                  FROM spfli ",
            "                 WHERE mandt = SESSION_CONTEXT( 'CLIENT' ); ",
            "",
            "",
            "    lt_spfli2 = SELECT carrid, connid, countryfr, countryto, ",
            "                       ROW_NUMBER ( ) OVER( PARTITION BY carrid, connid ",
            "                                            ORDER BY \"CARRID\", connid ASC ",
            "                                          ) AS \"ROW_ID\" ",
            "                  FROM spfli ",
            "                 WHERE mandt = SESSION_CONTEXT( 'CLIENT' ); ",
            "    --ENDMETHOD. ",
            "   ENDMETHOD.",
            " ENDCLASS."
        ));
        // @formatter:on

        // settings: lineBreakAfterCommaReq = false, all no-lb flags = false
        assertEquals(expected, prettyPrint(buildFullSqlScriptSource(), settings(false, false, false, false)));
    }

    /**
     * Semicolon at new line
     */
    @Test
    public void simpleTest() throws Exception {
     // @formatter:off
        List<String> source = lines(
            "   METHOD sel_data",
            "   BY DATABASE PROCEDURE FOR HDB LANGUAGE SQLSCRIPT",
            "   OPTIONS READ-ONLY.",
            "",
            " lt_bla = SELECT 'Hello' AS str FROM dummy",
            ";",
            "",
            "",
            "   ENDMETHOD.",
            ""
        );


        List<String> expected = rtrim(lines(
           "   METHOD sel_data",
            "   BY DATABASE PROCEDURE FOR HDB LANGUAGE SQLSCRIPT",
            "   OPTIONS READ-ONLY.",
            "",
            "    lt_bla = SELECT 'Hello' AS str",
            "               FROM dummy",
            "                    ; ",
            "",
            "",
            "   ENDMETHOD.",
            ""
        ));
        // @formatter:on
        List<String> actual = prettyPrint(source, standardSettings());
        assertEquals(expected, actual);
    }

    /**
     * Method Point at new line
     */
    @Test
    public void methodPointAtNewLine() throws Exception {
     // @formatter:off
        List<String> source = lines(
            "   METHOD sel_data",
            "   BY DATABASE PROCEDURE FOR HDB LANGUAGE SQLSCRIPT",
            "   OPTIONS READ-ONLY",
            "   .",
            "",
            " lt_bla = SELECT dummy.dummy AS str", 
            "               3 as bla,    ",
            "               dummy.dummy AS str2",
            "              FROM dummy",
            ";",
            "",
            "",
            "   ENDMETHOD.",
            ""
        );


        List<String> expected = rtrim(lines(
           "   METHOD sel_data",
            "   BY DATABASE PROCEDURE FOR HDB LANGUAGE SQLSCRIPT",
            "   OPTIONS READ-ONLY",
            "   .",
            "",
            "    lt_bla = SELECT dummy.dummy AS str",
            "                    3 AS bla,",
            "                    dummy.dummy AS str2",
            "               FROM dummy",
            "                    ; ",
            "",
            "",
            "   ENDMETHOD.",
            ""
        ));
        // @formatter:on
        List<String> actual = prettyPrint(source, standardSettings());
        assertEquals(expected, actual);
    }
}
